<a href="https://colab.research.google.com/github/ignaciomontovio/TP1Parte2PrograConc/blob/python/Python/TP1_Parte_2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import random
import numpy
import threading
import time

MAX_THREADS = 5
ROW = 5
COLUMN = 5
MAX_NUMBER = 23
MIN_NUMBER = -23

CS = numpy.empty(
    (ROW, COLUMN),
    int,
)
CC = numpy.empty(
    (ROW, COLUMN),
    int,
)


def get_number():
    return random.randrange(MIN_NUMBER, MAX_NUMBER)


def get_sum(row_a, row_b, row_number):
    for i in range(COLUMN):
        CC[row_number][i] = row_a[i] + row_b[i]


def sum_sec(m1, m2):
    for i in range(ROW):
        for j in range(COLUMN):
            CS[i][j] = m1[i][j] + m2[i][j]


def sum_con(m1, m2):
    threads = []
    CC = numpy.empty((ROW, COLUMN), int)
    for i in range(MAX_THREADS):
        threads.append(
            threading.Thread(
                target=get_sum,
                args=(m1[i], m2[i], i),
                daemon=False,
            )
        )
    for i in range(MAX_THREADS):
        threads[i].start()
    for i in range(MAX_THREADS):
        threads[i].join()


def compare():
    if numpy.equal(CS, CC).all():
        print(
            "Las matrices resultantes son iguales",
        )
        return
    print(
        "Las matrices resultantes no son iguales",
    )
    return


def show_data(m1, m2):
    print(
        "Matriz 1",
        "\n",
        m1,
        "\n",
    )
    print(
        "Matriz 2",
        "\n",
        m2,
        "\n",
    )
    print(
        "Matriz CS",
        "\n",
        CS,
        "\n",
    )
    print(
        "Matriz CC",
        "\n",
        CC,
        "\n",
    )
    compare()


def set_data():
    m = numpy.array(
        [
            [
                get_number(),
                get_number(),
                get_number(),
                get_number(),
                get_number(),
            ],
            [
                get_number(),
                get_number(),
                get_number(),
                get_number(),
                get_number(),
            ],
            [
                get_number(),
                get_number(),
                get_number(),
                get_number(),
                get_number(),
            ],
            [
                get_number(),
                get_number(),
                get_number(),
                get_number(),
                get_number(),
            ],
            [
                get_number(),
                get_number(),
                get_number(),
                get_number(),
                get_number(),
            ],
        ]
    )
    return m


def main():
    m1 = set_data()
    m2 = set_data()
    sum_sec(m1, m2)
    sum_con(m1, m2)
    show_data(m1, m2)


if __name__ == "__main__":
    main()


Matriz 1 
 [[-152   60 -132  -36 -140]
 [ -84   36   36  -72   76]
 [ -60  -48  -12   56   60]
 [ -60    8   36  -20  -56]
 [ -28  -48  -16   84  -92]] 

Matriz 2 
 [[-152   60 -132  -36 -140]
 [ -84   36   36  -72   76]
 [ -60  -48  -12   56   60]
 [ -60    8   36  -20  -56]
 [ -28  -48  -16   84  -92]] 

Matriz CS 
 [[-304  120 -264  -72 -280]
 [-168   72   72 -144  152]
 [-120  -96  -24  112  120]
 [-120   16   72  -40 -112]
 [ -56  -96  -32  168 -184]] 

Matriz CC 
 [[-304  120 -264  -72 -280]
 [-168   72   72 -144  152]
 [-120  -96  -24  112  120]
 [-120   16   72  -40 -112]
 [ -56  -96  -32  168 -184]] 

Las matrices resultantes son iguales


Utilizo numpy porque es mas comodo para visualizar las matrices pero no utilizo la funcion de suma entre matrices que proporciona, porque no se si es secuencial o concurrente.